name: Coveralls

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  test:
    name: Run Backend Tests and Report Coverage
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd LetrasProhibidas/backend
          npm install

      - name: Wait 2 minutes  for Others Jobs
        run: sleep 120

      - name: Run Tests
        env:
          MONGODB_URI_TEST: ${{ secrets.MONGODB_URI_TEST }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          cd LetrasProhibidas/backend
          npm test

      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          path-to-lcov: LetrasProhibidas/backend/coverage/lcov.info
