name: Coveralls

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  test:
    name: Run Backend Tests and Report Coverage
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd LetrasProhibidas/backend
          npm install

      - name: Wait for Run-Test-Backend Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            const { data: runs } = await octokit.rest.actions.listWorkflowRuns({
              owner: 'SyTW2425',
              repo: 'ProyectoE08',
              workflow_id: 'Run-Test-Backend.yml',
              status: 'completed'
            });
            if (runs.workflow_runs.length === 0) {
              throw new Error('No completed runs found for Run-Test-Backend.yml');
            }

      - name: Run Tests
        env:
          MONGODB_URI_TEST: ${{ secrets.MONGODB_URI_TEST }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          cd LetrasProhibidas/backend
          npm test

      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          path-to-lcov: LetrasProhibidas/backend/coverage/lcov.info
